spring.application.name=transfer-service
server.port=8081
wallet-service.base-url=${WALLET_SERVICE_BASE_URL:http://localhost:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/transfer}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:transfer}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:transfer}
spring.jpa.hibernate.ddl-auto=update

